# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('original_size', models.BigIntegerField()),
                ('final_size', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('device_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('ext', models.CharField(max_length=25)),
                ('release_date', models.DateField()),
                ('duration', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_audio', models.BooleanField(default=True)),
                ('file_encoded', models.FileField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mule.User')),
            ],
        ),
        migrations.AddField(
            model_name='statistic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='mule.User'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mule.Video'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mule.PlayList'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='mule.User'),
        ),
    ]
